package agentbudget

// Code generated by scripts/generate_pricing.py from pricing.json — DO NOT EDIT.

import (
	"strings"
	"sync"
	"unicode"
)

// priceEntry stores per-token prices (not per-million).
type priceEntry struct {
	inputPerToken  float64
	outputPerToken float64
}

// builtinPricing holds the default pricing table.
// All prices are stored as cost-per-token (i.e. price-per-million / 1_000_000).
var builtinPricing = map[string]priceEntry{

	// OpenAI
	"gpt-4o":                   {2.5 / 1e6, 10 / 1e6},
	"gpt-4o-2024-11-20":        {2.5 / 1e6, 10 / 1e6},
	"gpt-4o-2024-08-06":        {2.5 / 1e6, 10 / 1e6},
	"gpt-4o-mini":              {0.15 / 1e6, 0.6 / 1e6},
	"gpt-4o-mini-2024-07-18":   {0.15 / 1e6, 0.6 / 1e6},
	"gpt-4.1":                  {2 / 1e6, 8 / 1e6},
	"gpt-4.1-mini":             {0.4 / 1e6, 1.6 / 1e6},
	"gpt-4.1-nano":             {0.1 / 1e6, 0.4 / 1e6},
	"gpt-4-turbo":              {10 / 1e6, 30 / 1e6},
	"gpt-4-turbo-2024-04-09":   {10 / 1e6, 30 / 1e6},
	"gpt-4":                    {30 / 1e6, 60 / 1e6},
	"gpt-3.5-turbo":            {0.5 / 1e6, 1.5 / 1e6},
	"o1":                       {15 / 1e6, 60 / 1e6},
	"o1-mini":                  {3 / 1e6, 12 / 1e6},
	"o1-preview":               {15 / 1e6, 60 / 1e6},
	"o3":                       {2 / 1e6, 8 / 1e6},
	"o3-mini":                  {1.1 / 1e6, 4.4 / 1e6},
	"o3-pro":                   {20 / 1e6, 80 / 1e6},
	"o4-mini":                  {1.1 / 1e6, 4.4 / 1e6},
	// Anthropic
	"claude-opus-4-6":          {5 / 1e6, 25 / 1e6},
	"claude-opus-4-5":          {5 / 1e6, 25 / 1e6},
	"claude-sonnet-4-5-20250929": {3 / 1e6, 15 / 1e6},
	"claude-sonnet-4-5":        {3 / 1e6, 15 / 1e6},
	"claude-sonnet-4":          {3 / 1e6, 15 / 1e6},
	"claude-haiku-4-5-20251001": {1 / 1e6, 5 / 1e6},
	"claude-haiku-4-5":         {1 / 1e6, 5 / 1e6},
	"claude-opus-4-20250514":   {15 / 1e6, 75 / 1e6},
	"claude-3-5-sonnet-20241022": {3 / 1e6, 15 / 1e6},
	"claude-3-5-sonnet-20240620": {3 / 1e6, 15 / 1e6},
	"claude-3-5-haiku-20241022": {0.8 / 1e6, 4 / 1e6},
	"claude-3-opus-20240229":   {15 / 1e6, 75 / 1e6},
	"claude-3-opus":            {15 / 1e6, 75 / 1e6},
	"claude-3-sonnet-20240229": {3 / 1e6, 15 / 1e6},
	"claude-3-sonnet":          {3 / 1e6, 15 / 1e6},
	"claude-3-haiku-20240307":  {0.25 / 1e6, 1.25 / 1e6},
	"claude-3-haiku":           {0.25 / 1e6, 1.25 / 1e6},
	// Google Gemini
	"gemini-2.5-pro":           {1.25 / 1e6, 10 / 1e6},
	"gemini-2.5-flash":         {0.3 / 1e6, 2.5 / 1e6},
	"gemini-2.5-flash-lite":    {0.1 / 1e6, 0.4 / 1e6},
	"gemini-2.0-flash":         {0.1 / 1e6, 0.4 / 1e6},
	"gemini-2.0-flash-lite":    {0.075 / 1e6, 0.3 / 1e6},
	"gemini-1.5-pro":           {1.25 / 1e6, 5 / 1e6},
	"gemini-1.5-pro-latest":    {1.25 / 1e6, 5 / 1e6},
	"gemini-1.5-flash":         {0.075 / 1e6, 0.3 / 1e6},
	"gemini-1.5-flash-latest":  {0.075 / 1e6, 0.3 / 1e6},
	"gemini-1.0-pro":           {0.5 / 1e6, 1.5 / 1e6},
	// Mistral
	"mistral-large-latest":     {0.5 / 1e6, 1.5 / 1e6},
	"mistral-large":            {0.5 / 1e6, 1.5 / 1e6},
	"mistral-small-latest":     {0.03 / 1e6, 0.11 / 1e6},
	"mistral-small":            {0.03 / 1e6, 0.11 / 1e6},
	"mistral-medium-latest":    {0.4 / 1e6, 2 / 1e6},
	"mistral-medium":           {0.4 / 1e6, 2 / 1e6},
	"codestral-latest":         {0.3 / 1e6, 0.9 / 1e6},
	"codestral":                {0.3 / 1e6, 0.9 / 1e6},
	"open-mistral-nemo":        {0.02 / 1e6, 0.04 / 1e6},
	// Cohere
	"command-r-plus":           {2.5 / 1e6, 10 / 1e6},
	"command-r":                {0.15 / 1e6, 0.6 / 1e6},
	"command-light":            {0.3 / 1e6, 0.6 / 1e6},
	"command":                  {1 / 1e6, 2 / 1e6},
}

var (
	customPricingMu sync.RWMutex
	customPricing   = map[string]priceEntry{}
)

// RegisterModel adds or overrides pricing for a model at runtime.
// Prices are in USD per million tokens.
func RegisterModel(model string, inputPerMillion, outputPerMillion float64) error {
	if inputPerMillion < 0 || outputPerMillion < 0 {
		return &InvalidBudget{Value: model + ": prices must be non-negative"}
	}
	customPricingMu.Lock()
	defer customPricingMu.Unlock()
	customPricing[model] = priceEntry{
		inputPerToken:  inputPerMillion / 1e6,
		outputPerToken: outputPerMillion / 1e6,
	}
	return nil
}

// getModelPricing returns the pricing entry for a model, or nil if not found.
// Lookup order: custom → builtin → fuzzy (strip date suffix) → OpenRouter prefix.
func getModelPricing(model string) *priceEntry {
	customPricingMu.RLock()
	defer customPricingMu.RUnlock()

	if e, ok := customPricing[model]; ok {
		return &e
	}
	if e, ok := builtinPricing[model]; ok {
		return &e
	}

	// Strip date suffix: "gpt-4o-2025-06-15" → "gpt-4o"
	if base := stripDateSuffix(model); base != model {
		if e, ok := customPricing[base]; ok {
			return &e
		}
		if e, ok := builtinPricing[base]; ok {
			return &e
		}
	}

	// OpenRouter prefix: "openai/gpt-4o" → "gpt-4o"
	if idx := strings.Index(model, "/"); idx != -1 {
		stripped := model[idx+1:]
		return getModelPricingNoLock(stripped)
	}

	return nil
}

// getModelPricingNoLock is used recursively; caller must hold customPricingMu.RLock.
func getModelPricingNoLock(model string) *priceEntry {
	if e, ok := customPricing[model]; ok {
		return &e
	}
	if e, ok := builtinPricing[model]; ok {
		return &e
	}
	if base := stripDateSuffix(model); base != model {
		if e, ok := customPricing[base]; ok {
			return &e
		}
		if e, ok := builtinPricing[base]; ok {
			return &e
		}
	}
	return nil
}

// stripDateSuffix removes trailing date-like segments from model names.
// e.g. "gpt-4o-2025-06-15" → "gpt-4o"
func stripDateSuffix(model string) string {
	parts := strings.Split(model, "-")
	for i := len(parts) - 1; i >= 1; i-- {
		seg := parts[i]
		if len(seg) == 4 && allDigits(seg) {
			return strings.Join(parts[:i], "-")
		}
	}
	return model
}

func allDigits(s string) bool {
	for _, r := range s {
		if !unicode.IsDigit(r) {
			return false
		}
	}
	return true
}

// CalculateCost returns the cost in USD for the given model and token counts.
// Returns (cost, true) if the model is found, (0, false) otherwise.
func CalculateCost(model string, inputTokens, outputTokens int64) (float64, bool) {
	p := getModelPricing(model)
	if p == nil {
		return 0, false
	}
	cost := float64(inputTokens)*p.inputPerToken + float64(outputTokens)*p.outputPerToken
	return cost, true
}
